FROM alpine

RUN wget -qO /tmp/ArmsAgent.zip "https://arms-apm-cn-shanghai.oss-cn-shanghai.aliyuncs.com/4.1.9/ArmsAgent.zip"; \
  mkdir -p /opt/ArmsAgent; \
  unzip /tmp/ArmsAgent.zip -d /opt/; \
  rm /tmp/ArmsAgent.zip
