FROM alpine

RUN wget -qO /tmp/ArmsAgent.zip "http://arms-apm-shanghai.oss-cn-shanghai.aliyuncs.com/ArmsAgent.zip"; \
  mkdir -p /opt/ArmsAgent; \
  unzip /tmp/ArmsAgent.zip -d /opt/; \
  rm /tmp/ArmsAgent.zip
