FROM alpine

RUN wget -qO /tmp/ArmsAgent.zip "https://arms-apm-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/2.7.3.5/ArmsAgent.zip"; \
  mkdir -p /opt/ArmsAgent; \
  unzip /tmp/ArmsAgent.zip -d /opt/; \
  rm /tmp/ArmsAgent.zip
