FROM alpine

RUN mkdir -p /opt/otel; \
 wget -qO /opt/otel/otel-javaagent.jar "https://nexus.onecontract-cloud.com/repository/oc-maven-group/io/hcbm/otel-javaagent/1.0/otel-javaagent-1.0.jar"; \
 wget -qO /opt/otel/otel-extension.jar "https://nexus.onecontract-cloud.com/repository/oc-maven-group/io/hcbm/otel-extension/1.0/otel-extension-1.0.jar"
