FROM alpine

RUN mkdir -p /opt/otel; \
 wget -qO /opt/otel/otel-javaagent.jar "http://nexus.saas.hand-china.com/repository/oc-release/io/hcbm/otel-javaagent/1.0/otel-javaagent-1.0.jar"; \
 wget -qO /opt/otel/otel-extension.jar "http://nexus.saas.hand-china.com/repository/oc-release/io/hcbm/otel-extension/1.0/otel-extension-1.0.jar"
