name: elasticsearch
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 5"
  push:
    paths:
      - "elasticsearch/**"
jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: |
          set -eux;
          for file_path in $(find elasticsearch -name Dockerfile | sort -r);
          do
            /usr/bin/docker buildx prune -a -f
            /usr/bin/docker buildx build --push --no-cache \
              --platform linux/amd64,linux/arm64 \
              --file ${file_path} \
              --tag ${{ secrets.DOCKERHUB_USERNAME }}/$(dirname $file_path | sed 's / : g') \
              ${file_path%/*}
          done
      - name: Build and push
        if: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
        run: |
          set -eux;
          for file_path in $(git diff --name-only HEAD~ HEAD | grep elasticsearch/ | grep Dockerfile);
          do
            /usr/bin/docker buildx prune -a -f
            /usr/bin/docker buildx build --push --no-cache \
              --platform linux/amd64,linux/arm64 \
              --file ${file_path} \
              --tag ${{ secrets.DOCKERHUB_USERNAME }}/$(dirname $file_path | sed 's / : g') \
              ${file_path%/*}
          done
