name: mirrors
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 5"
jobs:
  rustsec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Mirror
        run: |
          set -eux;
          org="rustsec"
          repos=("advisory-db")
          for repo in ${repos[*]}
          do
              git clone https://github.com/${org}/${repo}.git
              cd ${repo}
              git remote add mirror https://oauth2:${{ secrets.GITCODE_TOKEN }}@gitcode.net/qq_29330659/${org}_${repo}.git
              git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
              cd ..
          done
