# ref: https://github.com/TimeBye/registry-manager
name: Sync images to C7N
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"
jobs:
  ghcr-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Ghcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            ghcr:
              registry: https://ghcr.io
              repositories:
                - fluxcd/helm-controller:v0.31.1
                - fluxcd/kustomize-controller:v0.35.0
                - fluxcd/notification-controller:v0.33.0
                - fluxcd/source-controller:v0.36.0
          sync-policy:
            from: ghcr
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: fluxcd/
                new: oc-tools/
              - old: open-telemetry/opentelemetry-operator/
                new: oc-tools/open-telemetry_
          EOF
          registry-manager sync -c config.yaml
  dockerhub-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Dockerhub Onecontract to C7N force
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - onecontract/apache-rocketmq
                - onecontract/apache-rocketmq-dashboard
                - onecontract/applicationinsights-agent
                - onecontract/arms-agent
                - onecontract/arthas
                - onecontract/cibase
                - onecontract/elasticsearch
                - onecontract/frontbase
                - onecontract/javabase
                - onecontract/jnlp-agent-auto
                - onecontract/jnlp-agent-python
                - onecontract/kibana
                - onecontract/mysql-backup
                - onecontract/nodebase
                - onecontract/oc-agi-base
                - onecontract/oc-infra-python-base
                - onecontract/rclone
                - onecontract/rustbase
          sync-policy:
            from: dockerhub
            to: c7n
            force: true
            dry-run: false
            replace:
              - old: onecontract/
                new: oc-tools/onecontract_
          EOF
          registry-manager sync -c config.yaml
      - name: Dockerhub to C7N force
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - curlimages/curl:latest
                - jenkins/jenkins:lts-jdk11
                - jenkins/jenkins:lts-jdk17
                - jenkins/jenkins:lts
                - kiwigrid/k8s-sidecar:latest
                - library/busybox:latest
                - library/httpd:latest
                - library/httpd:2.4
                - library/nginx:latest
                - library/nginx:stable
                - library/nginx:1.24
                - library/mysql:5.7
                - library/mysql:8.0
                - library/rabbitmq:3.9-management
                - library/rabbitmq:3.10-management
                - library/rabbitmq:3.11-management
                - library/rabbitmq:3.12-management
                - library/redis:6.0
                - library/redis:6.2
                - library/redis:7.0
                - library/zookeeper:3.6-temurin
                - library/zookeeper:3.7-temurin
                - library/zookeeper:3.8-temurin
                - minio/minio:latest
          sync-policy:
            from: dockerhub
            to: c7n
            force: true
            dry-run: false
            replace:
              - old: curlimages/
                new: oc-tools/curlimages_
              - old: jenkins/
                new: oc-tools/jenkins_
              - old: kiwigrid/
                new: oc-tools/kiwigrid_
              - old: library
                new: oc-tools
              - old: minio/
                new: oc-tools/minio_
          EOF
          registry-manager sync -c config.yaml
      - name: Dockerhub to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - apache/skywalking-java-agent:8.16.0-alpine
                - apache/skywalking-oap-server:9.5.0
                - apache/skywalking-ui:9.5.0
                - fatedier/frps:v0.51.1
                - fatedier/frpc:v0.51.1
                - grafana/grafana:10.0.2
                - grafana/grafana:9.5.6
                - grafana/loki:2.8.3
                - grafana/promtail:2.8.3
                - istio/install-cni:1.14.5
                - istio/operator:1.14.5
                - istio/pilot:1.14.5
                - istio/proxyv2:1.14.5
                - istio/install-cni:1.15.3
                - istio/operator:1.15.3
                - istio/pilot:1.15.3
                - istio/proxyv2:1.15.3
                - jenkins/jenkins:2.401.2-lts-jdk11
                - jimmidyson/configmap-reload:v0.9.0
                - library/httpd:2.4.57
                - library/mysql:5.7.42
                - library/mysql:8.0.33
                - library/nginx:1.24.0
                - library/postgres:15.3
                - library/rabbitmq:3.9.29-management
                - library/rabbitmq:3.10.25-management
                - library/rabbitmq:3.11.20-management
                - library/rabbitmq:3.12.2-management
                - library/redis:6.0.20
                - library/redis:6.2.13
                - library/redis:7.0.12
                - library/zookeeper:3.7.1-temurin
                - library/zookeeper:3.8.1-temurin
                - minio/operator:v5.0.6
                - minio/minio:RELEASE.2023-07-18T17-49-40Z
                - nacos/nacos-server:v2.2.3
                - sonatype/nexus3:3.58.0
          sync-policy:
            from: dockerhub
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: apache/
                new: oc-tools/apache_
              - old: fatedier/
                new: oc-tools/fatedier_
              - old: grafana/
                new: oc-tools/grafana_
              - old: istio/
                new: oc-tools/istio_
              - old: jenkins/
                new: oc-tools/jenkins_
              - old: jimmidyson/
                new: oc-tools/jimmidyson_
              - old: library
                new: oc-tools
              - old: minio/
                new: oc-tools/minio_
              - old: nacos/
                new: oc-tools/nacos_
              - old: sonatype/
                new: oc-tools/sonatype_
          EOF
          registry-manager sync -c config.yaml
  quay-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Quay to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            quay:
              registry: https://quay.io
              repositories:
                - argoproj/argocli:v3.3.5
                - argoproj/argoexec:v3.3.5
                - argoproj/workflow-controller:v3.3.5
                - coreos/etcd:v3.5.4
                - jetstack/cert-manager-cainjector:v1.8.0
                - jetstack/cert-manager-controller:v1.8.0
                - jetstack/cert-manager-webhook:v1.8.0
          sync-policy:
            from: quay
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: argoproj/
                new: oc-tools/argoproj_
              - old: coreos/
                new: oc-tools/coreos_
              - old: jetstack/
                new: oc-tools/jetstack_
          EOF
          registry-manager sync -c config.yaml
  gcr-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Gcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://gcr.io
              repositories:
                - kubebuilder/kube-rbac-proxy:v0.8.0
          sync-policy:
            from: gcr
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: kubebuilder/
                new: oc-tools/kubebuilder_
          EOF
          registry-manager sync -c config.yaml
      - name: K8S Gcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://registry.k8s.io
              repositories:
                - defaultbackend-amd64:1.5
                - descheduler/descheduler:v0.25.1
                - ingress-nginx/controller:v1.5.1
                - ingress-nginx/kube-webhook-certgen:v1.3.0
                - kube-state-metrics/kube-state-metrics:v2.4.2
                - node-problem-detector/node-problem-detector:v0.8.10
          sync-policy:
            from: gcr
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: descheduler/
                new: oc-tools/descheduler_
              - old: ingress-nginx/
                new: oc-tools/ingress-nginx_
              - old: kube-state-metrics/
                new: oc-tools/prometheus_
              - old: node-problem-detector/
                new: oc-tools/node-problem-detector_
              - new: oc-tools
          EOF
          registry-manager sync -c config.yaml
  gitlab-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Gitlab to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://registry.gitlab.com
              repositories:
                - gitlab-org/gitlab-runner:alpine-v14.10.1
                - gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-f761588f
          sync-policy:
            from: gcr
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: gitlab-org/gitlab-runner/
                new: oc-tools/
              - old: gitlab-org/
                new: oc-tools/
          EOF
          registry-manager sync -c config.yaml
