# ref: https://github.com/TimeBye/registry-manager
name: Sync images to C7N
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
jobs:
  ghcr-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Ghcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            ghcr:
              registry: https://ghcr.io
              repositories:
                - fluxcd/helm-controller:v0.37.2
                - fluxcd/kustomize-controller:v1.2.1
                - fluxcd/notification-controller:v1.2.3
                - fluxcd/source-controller:v1.2.3
          sync-policy:
            from: ghcr
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: fluxcd/
                new: oc-tools/
              - old: open-telemetry/opentelemetry-operator/
                new: oc-tools/open-telemetry_
          EOF
          registry-manager sync -c config.yaml
  dockerhub-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      FROM_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      FROM_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Dockerhub Onecontract to C7N force
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              username: $FROM_USERNAME
              password: $FROM_PASSWORD
              repositories:
                - onecontract/apache-rocketmq
                - onecontract/apache-rocketmq-dashboard
                - onecontract/applicationinsights-agent
                - onecontract/arms-agent
                - onecontract/arthas
                - onecontract/backup
                - onecontract/cibase
                - onecontract/elasticsearch
                - onecontract/frontbase
                - onecontract/golangbase
                - onecontract/javabase
                - onecontract/jnlp-agent-auto
                - onecontract/jnlp-agent-python
                - onecontract/nodebase
                - onecontract/oc-agi-base
                - onecontract/oc-infra-python-base
                - onecontract/rustbase
          sync-policy:
            from: dockerhub
            to: c7n
            force: true
            dry-run: false
            replace:
              - old: onecontract/
                new: oc-tools/onecontract_
          EOF
          registry-manager sync -c config.yaml
  quay-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Quay to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            quay:
              registry: https://quay.io
              repositories:
                - argoproj/argocli:v3.5.2
                - argoproj/argoexec:v3.5.2
                - argoproj/workflow-controller:v3.5.2
                - coreos/etcd:v3.5.4
                - jetstack/cert-manager-cainjector:v1.8.0
                - jetstack/cert-manager-controller:v1.8.0
                - jetstack/cert-manager-webhook:v1.8.0
          sync-policy:
            from: quay
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: argoproj/
                new: oc-tools/argoproj_
              - old: coreos/
                new: oc-tools/coreos_
              - old: jetstack/
                new: oc-tools/jetstack_
          EOF
          registry-manager sync -c config.yaml
  gcr-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Gcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://gcr.io
              repositories:
                - kubebuilder/kube-rbac-proxy:v0.8.0
          sync-policy:
            from: gcr
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: kubebuilder/
                new: oc-tools/kubebuilder_
          EOF
          registry-manager sync -c config.yaml
      - name: K8S Gcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            k8s:
              registry: https://registry.k8s.io
              repositories:
                - defaultbackend-amd64:1.5
                - descheduler/descheduler:v0.25.1
                - ingress-nginx/controller:v1.11.2
                - ingress-nginx/kube-webhook-certgen:v1.4.3
                - kube-state-metrics/kube-state-metrics:v2.4.2
                - node-problem-detector/node-problem-detector:v0.8.10
          sync-policy:
            from: k8s
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: descheduler/
                new: oc-tools/descheduler_
              - old: ingress-nginx/
                new: oc-tools/ingress-nginx_
              - old: kube-state-metrics/
                new: oc-tools/prometheus_
              - old: node-problem-detector/
                new: oc-tools/node-problem-detector_
              - new: oc-tools
          EOF
          registry-manager sync -c config.yaml
  elastic-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Elastic to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            elastic:
              registry: https://docker.elastic.co
              repositories:
                - kibana/kibana:7.10.2
                - kibana/kibana:7.14.0
          sync-policy:
            from: elastic
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: kibana/
                new: oc-tools/
          EOF
          registry-manager sync -c config.yaml
  gitlab-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Gitlab to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gitlab:
              registry: https://registry.gitlab.com
              repositories:
                - gitlab-org/gitlab-runner:alpine-v15.8.3
                - gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-v15.8.3
          sync-policy:
            from: gitlab
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: gitlab-org/gitlab-runner/
                new: oc-tools/
              - old: gitlab-org/
                new: oc-tools/
          EOF
          registry-manager sync -c config.yaml
  oracle-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Oracle to C7N force
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://container-registry.oracle.com
              repositories:
                - database/free:latest
                - database/express:latest
          sync-policy:
            from: gcr
            to: c7n
            force: true
            dry-run: false
            replace:
              - old: database/
                new: oc-tools/oracle_database_
          EOF
          registry-manager sync -c config.yaml
      - name: Oracle to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://container-registry.oracle.com
              repositories:
                - database/free:23.3.0.0
                - database/express:21.3.0-xe
                - database/express:18.4.0-xe
          sync-policy:
            from: gcr
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: database/
                new: oc-tools/oracle_database_
          EOF
          registry-manager sync -c config.yaml
  crl5d-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: cr.l5d to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            crl5d:
              registry: https://cr.l5d.io
              repositories:
                - linkerd/policy-controller:edge-24.3.1
                - linkerd/proxy:edge-24.3.1
                - linkerd/proxy-init:v2.2.4
                - linkerd/controller:edge-24.3.1
                - linkerd/debug:edge-24.3.1
                - linkerd/metrics-api:edge-24.3.1
                - linkerd/tap:edge-24.3.1
                - linkerd/web:edge-24.3.1
                - linkerd/extension-init:v0.1.0
          sync-policy:
            from: crl5d
            to: c7n
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: linkerd/
                new: oc-tools/linkerd_
          EOF
          registry-manager sync -c config.yaml
