# ref: https://github.com/TimeBye/registry-manager
name: Sync images to C7N
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"
jobs:
  ghcr-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
    steps:
      - name: Ghcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            ghcr:
              registry: https://ghcr.io
              repositories:
                - fluxcd/helm-controller:v0.22.2
                - fluxcd/kustomize-controller:v0.26.3
                - fluxcd/notification-controller:v0.24.1
                - fluxcd/source-controller:v0.25.10
                - open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.48.0
          sync-policy:
            from: ghcr
            to: c7n
            dry-run: false
            replace:
              - old: fluxcd/
                new: oc-tools/
              - old: open-telemetry/opentelemetry-operator/
                new: oc-tools/open-telemetry_
          EOF
          registry-manager sync -c config.yaml
  dockerhub-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
    steps:
      - name: Dockerhub Onecontract to C7N force
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - onecontract/apache-rocketmq
                - onecontract/apache-rocketmq-dashboard
                - onecontract/applicationinsights-agent
                - onecontract/arms-agent
                - onecontract/arthas
                - onecontract/cibase
                - onecontract/elasticsearch
                - onecontract/frontbase
                - onecontract/javabase
                - onecontract/jnlp-agent-auto
                - onecontract/jnlp-agent-python
                - onecontract/kibana
                - onecontract/mysql-backup
                - onecontract/nodebase
                - onecontract/oc-infra-python-base
                - onecontract/otel-javaagent
                - onecontract/rclone
                - onecontract/rustbase
                - onecontract/srm-agent-call-chain
          sync-policy:
            from: dockerhub
            to: c7n
            force: true
            dry-run: false
            replace:
              - old: onecontract/
                new: oc-tools/onecontract_
          EOF
          registry-manager sync -c config.yaml
      - name: Dockerhub to C7N force
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - curlimages/curl:latest
                - jenkins/jenkins:lts-jdk11
                - jenkins/jenkins:lts-jdk17
                - jenkins/jenkins:lts
                - kiwigrid/k8s-sidecar:latest
                - library/busybox:latest
                - library/httpd:latest
                - library/httpd:2.4
                - library/nginx:latest
                - library/nginx:stable
                - library/nginx:1.22
                - library/mysql:5.7
                - library/mysql:8.0
                - library/rabbitmq:3.9-management
                - library/rabbitmq:3.10-management
                - library/rabbitmq:3.11-management
                - library/redis:6.0
                - library/redis:6.2
                - library/redis:7.0
                - library/zookeeper:3.6-temurin
                - library/zookeeper:3.7-temurin
                - library/zookeeper:3.8-temurin
                - minio/minio:latest
          sync-policy:
            from: dockerhub
            to: c7n
            force: true
            dry-run: false
            replace:
              - old: curlimages/
                new: oc-tools/curlimages_
              - old: jenkins/
                new: oc-tools/jenkins_
              - old: kiwigrid/
                new: oc-tools/kiwigrid_
              - old: library
                new: oc-tools
              - old: minio/
                new: oc-tools/minio_
          EOF
          registry-manager sync -c config.yaml
      - name: Dockerhub to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - apache/skywalking-java-agent:8.11.0-alpine
                - apache/skywalking-oap-server:9.1.0
                - apache/skywalking-ui:9.1.0
                - fatedier/frps:v0.44.0
                - fatedier/frpc:v0.44.0
                - grafana/grafana:9.3.1
                - grafana/loki:2.7.1
                - grafana/promtail:2.7.1
                - hengyunabc/arthas:3.6.2-no-jdk
                - istio/install-cni:1.14.5
                - istio/operator:1.14.5
                - istio/pilot:1.14.5
                - istio/proxyv2:1.14.5
                - istio/install-cni:1.15.3
                - istio/operator:1.15.3
                - istio/pilot:1.15.3
                - istio/proxyv2:1.15.3
                - jaegertracing/jaeger-query:1.32
                - jenkins/jenkins:2.375.1-lts-jdk11
                - jettech/kube-webhook-certgen:v1.5.2
                - jimmidyson/configmap-reload:v0.7.1
                - library/httpd:2.4.54
                - library/mysql:5.7.40
                - library/mysql:8.0.31
                - library/nginx:1.22.1
                - library/postgres:12.13
                - library/rabbitmq:3.9.27-management
                - library/rabbitmq:3.10.13-management
                - library/rabbitmq:3.11.5-management
                - library/redis:6.0.16
                - library/redis:6.2.8
                - library/redis:7.0.7
                - library/zookeeper:3.5.9-temurin
                - library/zookeeper:3.6.3-temurin
                - library/zookeeper:3.7.1-temurin
                - library/zookeeper:3.8.0-temurin
                - minio/operator:v4.4.26
                - minio/minio:RELEASE.2022-07-17T15-43-14Z
                - nacos/nacos-server:v2.1.2
                - otel/opentelemetry-collector-contrib:0.50.0
                - sonatype/nexus3:3.40.1
                - timescale/promscale:0.11.0
                - timescale/timescaledb-ha:pg13.7-ts2.7.0-p6
                - zqiannnn/prometheus-alert:v4.8.1
          sync-policy:
            from: dockerhub
            to: c7n
            dry-run: false
            replace:
              - old: apache/
                new: oc-tools/apache_
              - old: fatedier/
                new: oc-tools/fatedier_
              - old: grafana/
                new: oc-tools/grafana_
              - old: hengyunabc/
                new: oc-tools/hengyunabc_
              - old: istio/
                new: oc-tools/istio_
              - old: jaegertracing/
                new: oc-tools/jaegertracing_
              - old: jenkins/
                new: oc-tools/jenkins_
              - old: jettech/
                new: oc-tools/jettech_
              - old: jimmidyson/
                new: oc-tools/jimmidyson_
              - old: library
                new: oc-tools
              - old: minio/
                new: oc-tools/minio_
              - old: nacos/
                new: oc-tools/nacos_
              - old: otel/
                new: oc-tools/otel_
              - old: sonatype/
                new: oc-tools/sonatype_
              - old: timescale/
                new: oc-tools/timescale_
              - old: zqiannnn/
                new: oc-tools/zqiannnn_
          EOF
          registry-manager sync -c config.yaml
  quay-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
    steps:
      - name: Quay to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            quay:
              registry: https://quay.io
              repositories:
                - argoproj/argocli:v3.3.8
                - argoproj/argoexec:v3.3.8
                - argoproj/workflow-controller:v3.3.8
                - coreos/etcd:v3.5.4
                - jetstack/cert-manager-cainjector:v1.8.0
                - jetstack/cert-manager-controller:v1.8.0
                - jetstack/cert-manager-webhook:v1.8.0
                - prometheus/alertmanager:v0.24.0
                - prometheus/node-exporter:v1.3.1
                - prometheus/pushgateway:v1.4.3
                - prometheus/prometheus:v2.36.0
                - prometheus-operator/prometheus-config-reloader:v0.56.3
                - prometheus-operator/prometheus-operator:v0.56.3
                - thanos/thanos:v0.27.0
          sync-policy:
            from: quay
            to: c7n
            dry-run: false
            replace:
              - old: argoproj/
                new: oc-tools/argoproj_
              - old: coreos/
                new: oc-tools/coreos_
              - old: jetstack/
                new: oc-tools/jetstack_
              - old: prometheus/
                new: oc-tools/prometheus_
              - old: prometheus-operator/
                new: oc-tools/prometheus_
              - old: thanos/
                new: oc-tools/thanos_
          EOF
          registry-manager sync -c config.yaml
  gcr-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
    steps:
      - name: Gcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://gcr.io
              repositories:
                - kubebuilder/kube-rbac-proxy:v0.8.0
          sync-policy:
            from: gcr
            to: c7n
            dry-run: false
            replace:
              - old: kubebuilder/
                new: oc-tools/kubebuilder_
          EOF
          registry-manager sync -c config.yaml
      - name: K8S Gcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://k8s.gcr.io
              repositories:
                - defaultbackend-amd64:1.5
                - descheduler/descheduler:v0.25.1
                - ingress-nginx/controller:v1.5.1
                - kube-state-metrics/kube-state-metrics:v2.4.2
                - node-problem-detector/node-problem-detector:v0.8.10
          sync-policy:
            from: gcr
            to: c7n
            dry-run: false
            replace:
              - old: descheduler/
                new: oc-tools/descheduler_
              - old: ingress-nginx/
                new: oc-tools/ingress-nginx_
              - old: kube-state-metrics/
                new: oc-tools/prometheus_
              - old: node-problem-detector/
                new: oc-tools/node-problem-detector_
              - new: oc-tools
          EOF
          registry-manager sync -c config.yaml
  gitlab-to-c7n:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
    steps:
      - name: Gitlab to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://registry.gitlab.com
              repositories:
                - gitlab-org/gitlab-runner:alpine-v14.10.1
                - gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-f761588f
          sync-policy:
            from: gcr
            to: c7n
            dry-run: false
            replace:
              - old: gitlab-org/gitlab-runner/
                new: oc-tools/
              - old: gitlab-org/
                new: oc-tools/
          EOF
          registry-manager sync -c config.yaml
