# ref: https://github.com/TimeBye/registry-manager
name: Sync images to C7N
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"
jobs:
  ghcr-to-c7n:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
    steps:
      - name: Ghcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            ghcr:
              registry: https://ghcr.io
              repositories:
                - fluxcd/helm-controller:v0.21.0
                - fluxcd/kustomize-controller:v0.25.0
                - fluxcd/notification-controller:v0.23.5
                - fluxcd/source-controller:v0.24.4
                - open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.48.0
          sync-policy:
            from: ghcr
            to: c7n
            dry-run: false
            replace:
              - old: fluxcd/
                new: oc-tools/
              - old: open-telemetry/opentelemetry-operator/
                new: oc-tools/open-telemetry_
          EOF
          registry-manager sync -c config.yaml
  dockerhub-to-c7n:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
    steps:
      - name: Dockerhub Onecontract to C7N force
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - onecontract/applicationinsights-agent
                - onecontract/arms-agent
                - onecontract/elasticsearch
                - onecontract/frontbase
                - onecontract/javabase
                - onecontract/jnlp-agent-auto
                - onecontract/jnlp-agent-python
                - onecontract/kibana
                - onecontract/mysql-backup
                - onecontract/oc-infra-python-base
                - onecontract/openvpn
                - onecontract/otel-javaagent
                - onecontract/rclone
                - onecontract/rustbase
                - onecontract/srm-agent-call-chain
          sync-policy:
            from: dockerhub
            to: c7n
            force: true
            dry-run: false
            replace:
              - old: onecontract/
                new: oc-tools/onecontract_
          EOF
          registry-manager sync -c config.yaml
      - name: Dockerhub to C7N force
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - curlimages/curl:latest
                - library/busybox:latest
                - library/httpd:latest
                - library/httpd:2.4
                - library/nginx:latest
                - library/nginx:stable
                - library/nginx:1.20
                - library/mysql:5.7
                - library/mysql:8.0
                - library/redis:5.0
                - library/redis:6.0
                - library/redis:6.2
                - library/redis:7.0
                - minio/minio:latest
          sync-policy:
            from: dockerhub
            to: c7n
            force: true
            dry-run: false
            replace:
              - old: curlimages/
                new: oc-tools/curlimages_
              - old: library
                new: oc-tools
              - old: minio/
                new: oc-tools/minio_
          EOF
          registry-manager sync -c config.yaml
      - name: Dockerhub to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - apache/skywalking-java-agent:8.10.0-alpine
                - apache/skywalking-oap-server:9.0.0
                - apache/skywalking-ui:9.0.0
                - grafana/grafana:8.5.5
                - grafana/loki:2.5.0
                - grafana/promtail:2.5.0
                - hengyunabc/arthas:3.6.1-no-jdk
                - istio/install-cni:1.14.0
                - istio/operator:1.14.0
                - istio/pilot:1.14.0
                - istio/proxyv2:1.14.0
                - jaegertracing/jaeger-query:1.32
                - jenkins/jenkins:2.350-jdk11
                - jettech/kube-webhook-certgen:v1.5.2
                - jimmidyson/configmap-reload:v0.7.1
                - library/httpd:2.4.53
                - library/mysql:5.7.38
                - library/mysql:8.0.29
                - library/nginx:1.22.0
                - library/postgres:12.11
                - library/redis:5.0.14
                - library/redis:6.0.16
                - library/redis:6.2.7
                - library/redis:7.0.0
                - minio/operator:v4.4.22
                - minio/minio:RELEASE.2022-06-02T02-11-04Z
                - otel/opentelemetry-collector-contrib:0.48.0
                - sonatype/nexus3:3.39.0
                - timescale/promscale:0.10.0
                - timescale/timescaledb-ha:pg13.4-ts2.4.2-p0
          sync-policy:
            from: dockerhub
            to: c7n
            dry-run: false
            replace:
              - old: apache/
                new: oc-tools/apache_
              - old: grafana/
                new: oc-tools/grafana_
              - old: hengyunabc/
                new: oc-tools/hengyunabc_
              - old: istio/
                new: oc-tools/istio_
              - old: jaegertracing/
                new: oc-tools/jaegertracing_
              - old: jenkins/
                new: oc-tools/jenkins_
              - old: jettech/
                new: oc-tools/jettech_
              - old: jimmidyson/
                new: oc-tools/jimmidyson_
              - old: library
                new: oc-tools
              - old: minio/
                new: oc-tools/minio_
              - old: otel/
                new: oc-tools/otel_
              - old: sonatype/
                new: oc-tools/sonatype_
              - old: timescale/
                new: oc-tools/timescale_
          EOF
          registry-manager sync -c config.yaml
  quay-to-c7n:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
    steps:
      - name: Quay to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            quay:
              registry: https://quay.io
              repositories:
                - argoproj/argocli:v3.3.6
                - argoproj/argoexec:v3.3.6
                - argoproj/workflow-controller:v3.3.6
                - jetstack/cert-manager-cainjector:v1.8.0
                - jetstack/cert-manager-controller:v1.8.0
                - jetstack/cert-manager-webhook:v1.8.0
                - kiwigrid/k8s-sidecar:1.18.1
                - prometheus/alertmanager:v0.24.0
                - prometheus/node-exporter:v1.3.1
                - prometheus/pushgateway:v1.4.3
                - prometheus/prometheus:v2.36.0
                - prometheus-operator/prometheus-config-reloader:v0.56.3
                - prometheus-operator/prometheus-operator:v0.56.3
                - thanos/thanos:v0.26.0
          sync-policy:
            from: quay
            to: c7n
            dry-run: false
            replace:
              - old: argoproj/
                new: oc-tools/argoproj_
              - old: jetstack/
                new: oc-tools/jetstack_
              - old: kiwigrid/
                new: oc-tools/kiwigrid_
              - old: prometheus/
                new: oc-tools/prometheus_
              - old: prometheus-operator/
                new: oc-tools/prometheus_
              - old: thanos/
                new: oc-tools/thanos_
          EOF
          registry-manager sync -c config.yaml
  gcr-to-c7n:
    runs-on: ubuntu-20.04
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.C7N_USERNAME }}
      TO_PASSWORD: ${{ secrets.C7N_PASSWORD }}
    steps:
      - name: Gcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://gcr.io
              repositories:
                - kubebuilder/kube-rbac-proxy:v0.8.0
          sync-policy:
            from: gcr
            to: c7n
            dry-run: false
            replace:
              - old: kubebuilder/
                new: oc-tools/kubebuilder_
          EOF
          registry-manager sync -c config.yaml
      - name: K8S Gcr to C7N
        run: |
          cat << EOF >config.yaml
          registries:
            c7n:
              registry: https://registry.choerodon.com.cn
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://k8s.gcr.io
              repositories:
                - defaultbackend-amd64:1.5
                - ingress-nginx/controller:v1.2.1
                - kube-state-metrics/kube-state-metrics:v2.4.2
                - node-problem-detector/node-problem-detector:v0.8.10
          sync-policy:
            from: gcr
            to: c7n
            dry-run: false
            replace:
              - old: ingress-nginx/
                new: oc-tools/ingress-nginx_
              - old: kube-state-metrics/
                new: oc-tools/prometheus_
              - old: node-problem-detector/
                new: oc-tools/node-problem-detector_
              - new: oc-tools
          EOF
          registry-manager sync -c config.yaml
