# ref: https://github.com/TimeBye/registry-manager
name: Sync images to Tencent
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
jobs:
  ghcr-to-tencent:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Ghcr to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            ghcr:
              registry: https://ghcr.io
              repositories:
                - fluxcd/helm-controller:v0.37.2
                - fluxcd/kustomize-controller:v1.2.1
                - fluxcd/notification-controller:v1.2.3
                - fluxcd/source-controller:v1.2.3
          sync-policy:
            from: ghcr
            to: tencentyun
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: fluxcd/
                new: onecontract-cloud/
              - old: open-telemetry/opentelemetry-operator/
                new: onecontract-cloud/open-telemetry_
          EOF
          registry-manager sync -c config.yaml
  dockerhub-to-tencent:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Dockerhub Onecontract to Tencent force
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - onecontract/apache-rocketmq
                - onecontract/apache-rocketmq-dashboard
                - onecontract/applicationinsights-agent
                - onecontract/arms-agent
                - onecontract/arthas
                - onecontract/cibase
                - onecontract/elasticsearch
                - onecontract/frontbase
                - onecontract/javabase
                - onecontract/jnlp-agent-auto
                - onecontract/jnlp-agent-python
                - onecontract/mysql-backup
                - onecontract/nodebase
                - onecontract/oc-agi-base
                - onecontract/oc-infra-python-base
                - onecontract/opengauss
                - onecontract/rclone
                - onecontract/rustbase
          sync-policy:
            from: dockerhub
            to: tencentyun
            force: true
            dry-run: false
            replace:
              - old: onecontract/
                new: onecontract-cloud/
          EOF
          registry-manager sync -c config.yaml
      - name: Dockerhub to Tencent force
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - curlimages/curl:latest
                - jenkins/jenkins:lts-jdk11
                - jenkins/jenkins:lts-jdk17
                - jenkins/jenkins:lts
                - kiwigrid/k8s-sidecar:latest
                - library/busybox:latest
                - library/busybox:stable
                - library/httpd:latest
                - library/httpd:2.4
                - library/nginx:latest
                - library/nginx:stable
                - library/nginx:1.24
                - library/mysql:5.7
                - library/mysql:8.0
                - library/phpmyadmin:latest
                - library/postgres:latest
                - library/postgres:16
                - library/postgres:15
                - library/rabbitmq:3.9-management
                - library/rabbitmq:3.10-management
                - library/rabbitmq:3.11-management
                - library/rabbitmq:3.12-management
                - library/redis:6.0
                - library/redis:6.2
                - library/redis:7.0
                - library/zookeeper:3.6-temurin
                - library/zookeeper:3.7-temurin
                - library/zookeeper:3.8-temurin
                - minio/minio:latest
          sync-policy:
            from: dockerhub
            to: tencentyun
            force: true
            dry-run: false
            replace:
              - old: curlimages/
                new: onecontract-cloud/curlimages_
              - old: jenkins/
                new: onecontract-cloud/jenkins_
              - old: kiwigrid/
                new: onecontract-cloud/kiwigrid_
              - old: library
                new: onecontract-cloud
              - old: minio/
                new: onecontract-cloud/minio_
          EOF
          registry-manager sync -c config.yaml
      - name: Dockerhub to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            dockerhub:
              registry: https://registry-1.docker.io
              repositories:
                - apache/skywalking-java-agent:8.16.0-alpine
                - apache/skywalking-oap-server:9.5.0
                - apache/skywalking-ui:9.5.0
                - fatedier/frps:v0.58.0
                - fatedier/frpc:v0.58.0
                - grafana/grafana:10.4.1
                - grafana/loki:2.9.6
                - grafana/promtail:2.9.6
                - istio/install-cni:1.14.5
                - istio/operator:1.14.5
                - istio/pilot:1.14.5
                - istio/proxyv2:1.14.5
                - istio/install-cni:1.15.3
                - istio/operator:1.15.3
                - istio/pilot:1.15.3
                - istio/proxyv2:1.15.3
                - jenkins/jenkins:2.401.2-lts-jdk11
                - jimmidyson/configmap-reload:v0.9.0
                - library/httpd:2.4.57
                - library/mysql:5.7.42
                - library/mysql:8.0.33
                - library/nginx:1.24.0
                - library/postgres:16.0
                - library/postgres:15.4
                - library/rabbitmq:3.8.34-management
                - library/rabbitmq:3.9.29-management
                - library/rabbitmq:3.10.25-management
                - library/rabbitmq:3.11.20-management
                - library/rabbitmq:3.12.2-management
                - library/redis:6.0.20
                - library/redis:6.2.13
                - library/redis:7.0.12
                - library/zookeeper:3.7.1-temurin
                - library/zookeeper:3.8.1-temurin
                - minio/operator:v5.0.6
                - minio/minio:RELEASE.2023-07-18T17-49-40Z
                - nacos/nacos-server:v2.2.3
                - prom/prometheus:v2.48.1
                - sonatype/nexus3:3.66.0
          sync-policy:
            from: dockerhub
            to: tencentyun
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: apache/
                new: onecontract-cloud/apache_
              - old: fatedier/
                new: onecontract-cloud/fatedier_
              - old: grafana/
                new: onecontract-cloud/grafana_
              - old: istio/
                new: onecontract-cloud/istio_
              - old: jenkins/
                new: onecontract-cloud/jenkins_
              - old: jimmidyson/
                new: onecontract-cloud/jimmidyson_
              - old: library
                new: onecontract-cloud
              - old: minio/
                new: onecontract-cloud/minio_
              - old: nacos/
                new: onecontract-cloud/nacos_
              - old: prom/
                new: onecontract-cloud/prom_
              - old: sonatype/
                new: onecontract-cloud/sonatype_
          EOF
          registry-manager sync -c config.yaml
  quay-to-tencent:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Quay to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            quay:
              registry: https://quay.io
              repositories:
                - argoproj/argocli:v3.5.2
                - argoproj/workflow-controller:v3.5.2
                - coreos/etcd:v3.5.4
                - jetstack/cert-manager-cainjector:v1.8.0
                - jetstack/cert-manager-controller:v1.8.0
                - jetstack/cert-manager-webhook:v1.8.0
          sync-policy:
            from: quay
            to: tencentyun
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: argoproj/
                new: onecontract-cloud/argoproj_
              - old: coreos/
                new: onecontract-cloud/coreos_
              - old: jetstack/
                new: onecontract-cloud/jetstack_
          EOF
          registry-manager sync -c config.yaml
  gcr-to-tencent:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Gcr to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://gcr.io
              repositories:
                - kubebuilder/kube-rbac-proxy:v0.8.0
          sync-policy:
            from: gcr
            to: tencentyun
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: kubebuilder/
                new: onecontract-cloud/kubebuilder_
          EOF
          registry-manager sync -c config.yaml
      - name: K8S Gcr to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://registry.k8s.io
              repositories:
                - defaultbackend-amd64:1.5
                - descheduler/descheduler:v0.25.1
                - ingress-nginx/controller:v1.9.6
                - ingress-nginx/kube-webhook-certgen:v20231226-1a7112e06
                - kube-state-metrics/kube-state-metrics:v2.4.2
                - node-problem-detector/node-problem-detector:v0.8.10
          sync-policy:
            from: gcr
            to: tencentyun
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: descheduler/
                new: onecontract-cloud/descheduler_
              - old: ingress-nginx/
                new: onecontract-cloud/ingress-nginx_
              - old: kube-state-metrics/
                new: onecontract-cloud/prometheus_
              - old: node-problem-detector/
                new: onecontract-cloud/node-problem-detector_
              - new: onecontract-cloud
          EOF
          registry-manager sync -c config.yaml
  elastic-to-tencent:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Elastic to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            elastic:
              registry: https://docker.elastic.co
              repositories:
                - kibana/kibana:7.10.2
                - kibana/kibana:7.14.0
          sync-policy:
            from: elastic
            to: tencentyun
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: kibana/
                new: onecontract-cloud/
          EOF
          registry-manager sync -c config.yaml
  gitlab-to-tencent:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Gitlab to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://registry.gitlab.com
              repositories:
                - gitlab-org/gitlab-runner:alpine-v14.10.1
                - gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-f761588f
          sync-policy:
            from: gcr
            to: tencentyun
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: gitlab-org/gitlab-runner/
                new: onecontract-cloud/
              - old: gitlab-org/
                new: onecontract-cloud/
          EOF
          registry-manager sync -c config.yaml
  oracle-to-tencent:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: Oracle to Tencent force
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://container-registry.oracle.com
              repositories:
                - database/free:latest
                - database/express:latest
          sync-policy:
            from: gcr
            to: tencentyun
            force: true
            dry-run: false
            replace:
              - old: database/
                new: onecontract-cloud/oracle_database_
          EOF
          registry-manager sync -c config.yaml
      - name: Oracle to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            gcr:
              registry: https://container-registry.oracle.com
              repositories:
                - database/free:23.3.0.0
                - database/express:21.3.0-xe
                - database/express:18.4.0-xe
          sync-policy:
            from: gcr
            to: tencentyun
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: database/
                new: onecontract-cloud/oracle_database_
          EOF
          registry-manager sync -c config.yaml
  crl5d-to-tencent:
    runs-on: ubuntu-latest
    container: setzero/registry-manager
    env:
      TO_USERNAME: ${{ secrets.TENCENT_USERNAME }}
      TO_PASSWORD: ${{ secrets.TENCENT_PASSWORD }}
      SYNC_POLICY_FORCE: ${{ vars.SYNC_POLICY_FORCE }}
    steps:
      - name: cr.l5d to Tencent
        run: |
          cat << EOF >config.yaml
          registries:
            tencentyun:
              registry: https://ccr.ccs.tencentyun.com
              username: $TO_USERNAME
              password: $TO_PASSWORD
            crl5d:
              registry: https://cr.l5d.io
              repositories:
                - linkerd/policy-controller:edge-24.3.1
                - linkerd/proxy:edge-24.3.1
                - linkerd/proxy-init:v2.2.4
                - linkerd/controller:edge-24.3.1
                - linkerd/debug:edge-24.3.1
                - linkerd/metrics-api:edge-24.3.1
                - linkerd/tap:edge-24.3.1
                - linkerd/web:edge-24.3.1
                - linkerd/extension-init:v0.1.0
          sync-policy:
            from: crl5d
            to: tencentyun
            force: $SYNC_POLICY_FORCE
            dry-run: false
            replace:
              - old: linkerd/
                new: onecontract-cloud/linkerd_
          EOF
          registry-manager sync -c config.yaml
